# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fedoralink.db.binary
import fedoralink.fields
import fedoralink.migration_ops
import fedoralink.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        fedoralink.migration_ops.FedoraCreateModel(
            name='ArrayFieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', fedoralink.fields.FedoraField(base_field=models.CharField(max_length=10), max_length=10, multiplicity=100000, rdf_name='http://cesnet.cz/ns/repository#a', rdf_namespace='http://cesnet.cz/ns/repository#')),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, unique=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'testapp_arrayfieldmodel', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#array_field_test', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#array_field_test']},
        ),
        fedoralink.migration_ops.FedoraCreateModel(
            name='BasicFieldTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=20)),
                ('text_field', models.TextField()),
                ('slug_field', models.SlugField()),
                ('url_field', models.URLField()),
                ('uuid_field', models.UUIDField()),
                ('int_field', models.IntegerField()),
                ('biginteger_field', models.BigIntegerField()),
                ('positive_integer_field', models.PositiveIntegerField()),
                ('positive_small_integer_field', models.PositiveSmallIntegerField()),
                ('small_integer_field', models.SmallIntegerField()),
                ('float_field', models.FloatField()),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('date_field', models.DateField()),
                ('time_field', models.TimeField()),
                ('datetime_field', models.DateTimeField()),
                ('duration_field', models.DurationField()),
                ('ip_field', models.GenericIPAddressField()),
                ('email', models.EmailField(max_length=254)),
                ('boolean_field', models.BooleanField()),
                ('null_boolean', models.NullBooleanField()),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, unique=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'testapp_basicfieldtypes', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#all_field_types', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#all_field_types']},
        ),
        fedoralink.migration_ops.FedoraCreateModel(
            name='BinaryFieldTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binary_field', models.BinaryField()),
                ('file', models.FileField(storage=fedoralink.db.binary.FedoraStorage(), upload_to='')),
                ('image', models.ImageField(storage=fedoralink.db.binary.FedoraStorage(), upload_to='')),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, unique=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'testapp_binaryfieldtypes', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#binary_field_types', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#binary_field_types']},
        ),
        fedoralink.migration_ops.FedoraCreateModel(
            name='Complex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=10)),
                ('b', models.CharField(max_length=10)),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, unique=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'testapp_complex', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#complex_type', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#complex_type']},
        ),
        fedoralink.migration_ops.FedoraCreateModel(
            name='InheritedA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, unique=True, verbose_name='Fedora resource URL')),
                ('a', models.CharField(max_length=10)),
            ],
            fedora_options={'default_parent': 'testapp_inheriteda', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#testapp_inheriteda', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#testapp_inheriteda', 'http://cesnet.cz/ns/repository#testapp_simple']},
        ),
        fedoralink.migration_ops.FedoraCreateModel(
            name='InheritedB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, unique=True, verbose_name='Fedora resource URL')),
                ('b', models.CharField(max_length=10)),
            ],
            fedora_options={'default_parent': 'testapp_inheritedb', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#testapp_inheritedb', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#testapp_inheritedb', 'http://cesnet.cz/ns/repository#testapp_simple']},
        ),
        fedoralink.migration_ops.FedoraCreateModel(
            name='JsonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_single', fedoralink.fields.JSONField(blank=True, null=True)),
                ('json_multiple', fedoralink.fields.FedoraField(base_field=fedoralink.fields.JSONField(blank=True, null=True), multiplicity=100000, rdf_name='http://cesnet.cz/ns/repository#json_multiple', rdf_namespace='http://cesnet.cz/ns/repository#')),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, unique=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'testapp_jsonmodel', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#json', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#json']},
        ),
        fedoralink.migration_ops.FedoraCreateModel(
            name='ModelWithForeignKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, unique=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'testapp_modelwithforeignkey', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#foreign', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#foreign']},
        ),
        fedoralink.migration_ops.FedoraCreateModel(
            name='ModelWithForeignKeyArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f', fedoralink.fields.FedoraField(base_field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.Simple'), multiplicity=100000, rdf_name='http://cesnet.cz/ns/repository#f', rdf_namespace='http://cesnet.cz/ns/repository#')),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, unique=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'testapp_modelwithforeignkeyarray', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#foreign_many', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#foreign_many']},
        ),
        fedoralink.migration_ops.FedoraCreateModel(
            name='ModelWithTwoForeignKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, unique=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'testapp_modelwithtwoforeignkeys', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#foreign2', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#foreign2']},
        ),
        fedoralink.migration_ops.FedoraCreateModel(
            name='Simple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, unique=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'testapp_simple', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#testapp_simple', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#testapp_simple']},
        ),
        fedoralink.migration_ops.FedoraAddField(
            model_name='modelwithtwoforeignkeys',
            name='f',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='testapp.Simple'),
            fedora_options={'model': {'default_parent': 'testapp_modelwithtwoforeignkeys', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#foreign2', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#foreign2']}, 'rdf_name': 'http://cesnet.cz/ns/repository#f', 'rdf_namespace': 'http://cesnet.cz/ns/repository#'},
        ),
        fedoralink.migration_ops.FedoraAddField(
            model_name='modelwithtwoforeignkeys',
            name='g',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='testapp.Simple'),
            fedora_options={'model': {'default_parent': 'testapp_modelwithtwoforeignkeys', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#foreign2', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#foreign2']}, 'rdf_name': 'http://cesnet.cz/ns/repository#g', 'rdf_namespace': 'http://cesnet.cz/ns/repository#'},
        ),
        fedoralink.migration_ops.FedoraAddField(
            model_name='modelwithforeignkey',
            name='f',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.Simple'),
            fedora_options={'model': {'default_parent': 'testapp_modelwithforeignkey', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#foreign', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#foreign']}, 'rdf_name': 'http://cesnet.cz/ns/repository#f', 'rdf_namespace': 'http://cesnet.cz/ns/repository#'},
        ),
    ]
