# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import fedoralink.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, verbose_name='Fedora resource URL')),
            ],
        ),
    ]
