# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import fedoralink.migration_ops
import fedoralink.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        fedoralink.migration_ops.FedoraCreateModel(
            name='Complex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=10)),
                ('b', models.CharField(max_length=10)),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'testapp_complex', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#complex_type', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#complex_type']},
        ),
    ]
