# Generated by Django 2.0 on 2017-09-17 19:06

from django.db import migrations, models
import fedoralink.fields
import fedoralink.migration_ops
import fedoralink.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        fedoralink.migration_ops.FedoraCreateModel(
            name='DifferentNamespace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=10)),
                ('b', fedoralink.fields.FedoraField(base_field=models.CharField(max_length=10), multiplicity=1, rdf_name='http://purl.org/dc/elements/1.1/b', rdf_namespace='http://cesnet.cz/ns/repository#')),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, unique=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'testapp_differentnamespace', 'field_options': None, 'primary_rdf_type': 'http://www.w3.org/ns/auth/acl#Authorization', 'rdf_namespace': 'http://www.w3.org/ns/auth/acl#', 'rdf_types': ['http://www.w3.org/ns/auth/acl#Authorization']},
        ),
    ]
