# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-05 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import fedoralink.fields
import fedoralink.migration_ops
import fedoralink.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        fedoralink.migration_ops.FedoraCreateModel(
            name='JsonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_single', fedoralink.fields.JSONField(blank=True, null=True)),
                ('json_multiple', fedoralink.fields.FedoraField(base_field=fedoralink.fields.JSONField(blank=True, null=True), multiplicity=100000, rdf_name='http://cesnet.cz/ns/repository#json_multiple', rdf_namespace='http://cesnet.cz/ns/repository#')),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, unique=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'testapp_jsonmodel', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#json', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#json']},
        ),
    ]
