# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import fedoralink.fields
import fedoralink.migration_ops
import fedoralink.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_complex'),
    ]

    operations = [
        fedoralink.migration_ops.FedoraCreateModel(
            name='ArrayFieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', fedoralink.fields.FedoraField(base_field=models.CharField(max_length=10), max_length=10, multiplicity=100000, rdf_name='http://cesnet.cz/ns/repository#a', rdf_namespace='http://cesnet.cz/ns/repository#')),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'testapp_arrayfieldmodel', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#array_field_test', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#array_field_test']},
        ),
    ]
