# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fedoralink.migration_ops


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_jsonmodel'),
    ]

    operations = [
        fedoralink.migration_ops.FedoraCreateModel(
            name='InheritedA',
            fields=[
                ('simple_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.Simple')),
                ('a', models.CharField(max_length=10)),
            ],
            bases=('testapp.simple',),
            fedora_options={'default_parent': 'testapp_inheriteda', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#testapp_inheriteda', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#testapp_inheriteda', 'http://cesnet.cz/ns/repository#testapp_simple']},
        ),
        fedoralink.migration_ops.FedoraCreateModel(
            name='InheritedB',
            fields=[
                ('simple_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.Simple')),
                ('b', models.CharField(max_length=10)),
            ],
            bases=('testapp.simple',),
            fedora_options={'default_parent': 'testapp_inheritedb', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#testapp_inheritedb', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#testapp_inheritedb', 'http://cesnet.cz/ns/repository#testapp_simple']},
        ),
    ]
