# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-14 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import fedoralink.migration_ops
import fedoralink.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_arrayfieldmodel'),
    ]

    operations = [
        fedoralink.migration_ops.FedoraCreateModel(
            name='BasicFieldTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=20)),
                ('text_field', models.TextField()),
                ('slug_field', models.SlugField()),
                ('url_field', models.URLField()),
                ('uuid_field', models.UUIDField()),
                ('int_field', models.IntegerField()),
                ('biginteger_field', models.BigIntegerField()),
                ('positive_integer_field', models.PositiveIntegerField()),
                ('positive_small_integer_field', models.PositiveSmallIntegerField()),
                ('small_integer_field', models.SmallIntegerField()),
                ('float_field', models.FloatField()),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('date_field', models.DateField()),
                ('time_field', models.TimeField()),
                ('datetime_field', models.DateTimeField()),
                ('duration_field', models.DurationField()),
                ('ip_field', models.GenericIPAddressField()),
                ('email', models.EmailField(max_length=254)),
                ('boolean_field', models.BooleanField()),
                ('null_boolean', models.NullBooleanField()),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'testapp_basicfieldtypes', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#all_field_types', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#all_field_types']},
        ),
    ]
