# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import fedoralink.db.binary
import fedoralink.migration_ops
import fedoralink.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_basicfieldtypes'),
    ]

    operations = [
        fedoralink.migration_ops.FedoraCreateModel(
            name='BinaryFieldTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binary_field', models.BinaryField()),
                ('file', models.FileField(storage=fedoralink.db.binary.FedoraStorage(), upload_to='')),
                ('image', models.ImageField(storage=fedoralink.db.binary.FedoraStorage(), upload_to='')),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'testapp_binaryfieldtypes', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#binary_field_types', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#binary_field_types']},
        ),
    ]
