# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-18 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fedoralink.migration_ops
import fedoralink.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_modelwithforeignkey'),
    ]

    operations = [
        fedoralink.migration_ops.FedoraCreateModel(
            name='ModelWithTwoForeignKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, unique=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'testapp_modelwithtwoforeignkeys', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#foreign2', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#foreign2']},
        ),
    ]
