# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import fedoralink.migration_ops
import fedoralink.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        fedoralink.migration_ops.FedoraCreateModel(
            name='BinaryObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, unique=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'fedoralink_binaryobject', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#fedoralink_binaryobject', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#fedoralink_binaryobject']},
        ),
        fedoralink.migration_ops.FedoraCreateModel(
            name='FedoraObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, unique=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'fedoralink_fedoraobject', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#fedoralink_fedoraobject', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#fedoralink_fedoraobject']},
        ),
    ]
