# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-18 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import fedoralink.db.binary
import fedoralink.fields
import fedoralink.migration_ops
import fedoralink.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        fedoralink.migration_ops.FedoraCreateModel(
            name='BinaryObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, unique=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'fedoralink_binaryobject', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#fedoralink_binaryobject', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#fedoralink_binaryobject']},
        ),
        fedoralink.migration_ops.FedoraCreateModel(
            name='FedoraObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, unique=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'fedoralink_fedoraobject', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository#fedoralink_fedoraobject', 'rdf_namespace': 'http://cesnet.cz/ns/repository#', 'rdf_types': ['http://cesnet.cz/ns/repository#fedoralink_fedoraobject']},
        ),
        fedoralink.migration_ops.FedoraCreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(verbose_name='Label')),
                ('template_view', models.FileField(null=True, storage=fedoralink.db.binary.FedoraStorage(), upload_to='')),
                ('template_edit', models.FileField(null=True, storage=fedoralink.db.binary.FedoraStorage(), upload_to='')),
                ('template_list_item', models.FileField(null=True, storage=fedoralink.db.binary.FedoraStorage(), upload_to='')),
                ('controller', models.TextField(verbose_name='Controller class')),
                ('rdf_types', fedoralink.fields.FedoraField(base_field=models.TextField(verbose_name='RDF types'), multiplicity=100000, rdf_name='http://cesnet.cz/ns/repository#rdf_types', rdf_namespace='http://cesnet.cz/ns/repository#')),
                ('model_description', models.CharField(max_length=2048, verbose_name='Model metadata description')),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, unique=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'fedoralink_resourcetype', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository/type#ResourceType', 'rdf_namespace': 'http://cesnet.cz/ns/repository/type#', 'rdf_types': ['http://cesnet.cz/ns/repository/type#ResourceType']},
        ),
        fedoralink.migration_ops.FedoraCreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, unique=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'fedoralink_template', 'field_options': None, 'primary_rdf_type': 'http://cesnet.cz/ns/repository/type#Template', 'rdf_namespace': 'http://cesnet.cz/ns/repository/type#', 'rdf_types': ['http://cesnet.cz/ns/repository/type#Template']},
        ),
    ]
