# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import fedoralink.fields
import fedoralink.migration_ops
import fedoralink.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        fedoralink.migration_ops.FedoraCreateModel(
            name='DCObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_handle', fedoralink.fields.FedoraField(base_field=models.CharField(max_length=255, null=True, unique=True, verbose_name='CESNET unique persistent object handle'), multiplicity=1, rdf_name='http://cesnet.cz/ns/repository#_handle', rdf_namespace='http://cesnet.cz/ns/repository#')),
                ('title', models.TextField(default='', verbose_name='Title')),
                ('creator', models.TextField(default='', verbose_name='Creator')),
                ('subject', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=255, verbose_name='Subject'), multiplicity=100000, rdf_name='http://purl.org/dc/elements/1.1/subject', rdf_namespace='http://purl.org/dc/elements/1.1/')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('publisher', models.CharField(default='', max_length=255, verbose_name='Publisher')),
                ('contributor', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=255, verbose_name='Contributor'), multiplicity=100000, rdf_name='http://purl.org/dc/elements/1.1/contributor', rdf_namespace='http://purl.org/dc/elements/1.1/')),
                ('date', models.CharField(default='', max_length=128, verbose_name='Date')),
                ('type', models.CharField(choices=[('Collection', 'Collection'), ('Dataset', 'Dataset'), ('Event', 'Event'), ('Image', 'Image'), ('InteractiveResource', 'InteractiveResource'), ('Service', 'Service'), ('Software', 'Software'), ('Sound', 'Sound'), ('Text', 'Text'), ('PhysicalObject', 'PhysicalObject')], default='Text', max_length=20, verbose_name='Type')),
                ('dformat', models.TextField(default='', verbose_name='Format')),
                ('identifier', models.CharField(default='', max_length=255, verbose_name='Identifier')),
                ('source', models.CharField(max_length=255, verbose_name='Source')),
                ('language', fedoralink.fields.FedoraField(base_field=models.CharField(max_length=128, verbose_name='Language'), multiplicity=100000, rdf_name='http://purl.org/dc/elements/1.1/language', rdf_namespace='http://purl.org/dc/elements/1.1/')),
                ('relation', models.TextField(default='', verbose_name='Relation')),
                ('coverage', models.CharField(default='', max_length=255, verbose_name='Coverage')),
                ('rights', fedoralink.fields.FedoraField(base_field=models.TextField(default='', verbose_name='Rights'), multiplicity=100000, rdf_name='http://purl.org/dc/elements/1.1/rights', rdf_namespace='http://purl.org/dc/elements/1.1/')),
                ('abstract', fedoralink.fields.FedoraField(base_field=models.TextField(default='', verbose_name='Abstract'), multiplicity=1, rdf_name='http://purl.org/dc/terms/abstract', rdf_namespace='http://purl.org/dc/terms/')),
                ('accessRights', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=255), multiplicity=1, rdf_name='http://purl.org/dc/terms/accessRights', rdf_namespace='http://purl.org/dc/terms/')),
                ('accrualMethod', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=255), multiplicity=1, rdf_name='http://purl.org/dc/terms/accrualMethod', rdf_namespace='http://purl.org/dc/terms/')),
                ('accrualPeriodicity', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=128), multiplicity=1, rdf_name='http://purl.org/dc/terms/accrualPeriodicity', rdf_namespace='http://purl.org/dc/terms/')),
                ('accrualPolicy', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=255), multiplicity=1, rdf_name='http://purl.org/dc/terms/accrualPolicy', rdf_namespace='http://purl.org/dc/terms/')),
                ('alternative', fedoralink.fields.FedoraField(base_field=models.TextField(default='', verbose_name='Alternative'), multiplicity=1, rdf_name='http://purl.org/dc/terms/alternative', rdf_namespace='http://purl.org/dc/terms/')),
                ('audience', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=255, verbose_name='Audience'), multiplicity=1, rdf_name='http://purl.org/dc/terms/audience', rdf_namespace='http://purl.org/dc/terms/')),
                ('available', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=128, verbose_name='Available'), multiplicity=1, rdf_name='http://purl.org/dc/terms/available', rdf_namespace='http://purl.org/dc/terms/')),
                ('bibliographicCitation', fedoralink.fields.FedoraField(base_field=models.TextField(default='', verbose_name='Bibliography'), multiplicity=1, rdf_name='http://purl.org/dc/terms/bibliographicCitation', rdf_namespace='http://purl.org/dc/terms/')),
                ('conformsTo', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=255), multiplicity=1, rdf_name='http://purl.org/dc/terms/conformsTo', rdf_namespace='http://purl.org/dc/terms/')),
                ('contributor_term', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=255, verbose_name='Contributor'), multiplicity=1, rdf_name='http://purl.org/dc/terms/contributor', rdf_namespace='http://purl.org/dc/terms/')),
                ('coverage_term', fedoralink.fields.FedoraField(base_field=models.CharField(default='', verbose_name='Coverage'), multiplicity=1, rdf_name='http://purl.org/dc/terms/coverage', rdf_namespace='http://purl.org/dc/terms/')),
                ('created', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=128, verbose_name='Created'), multiplicity=1, rdf_name='http://purl.org/dc/terms/created', rdf_namespace='http://purl.org/dc/terms/')),
                ('creator_term', fedoralink.fields.FedoraField(base_field=models.TextField(default='', verbose_name='Creator'), multiplicity=1, rdf_name='http://purl.org/dc/terms/creator', rdf_namespace='http://purl.org/dc/terms/')),
                ('date_term', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=128, verbose_name='Date'), multiplicity=1, rdf_name='http://purl.org/dc/terms/date', rdf_namespace='http://purl.org/dc/terms/')),
                ('dateAccepted', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=128, verbose_name='Accepted'), multiplicity=1, rdf_name='http://purl.org/dc/terms/dateAccepted', rdf_namespace='http://purl.org/dc/terms/')),
                ('dateCopyrighted', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=128, verbose_name='Copyrighted'), multiplicity=1, rdf_name='http://purl.org/dc/terms/dateCopyrighted', rdf_namespace='http://purl.org/dc/terms/')),
                ('dateSubmitted', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=128, verbose_name='Submitted'), multiplicity=1, rdf_name='http://purl.org/dc/terms/dateSubmitted', rdf_namespace='http://purl.org/dc/terms/')),
                ('description_term', fedoralink.fields.FedoraField(base_field=models.TextField(default='', verbose_name='Description'), multiplicity=1, rdf_name='http://purl.org/dc/terms/description', rdf_namespace='http://purl.org/dc/terms/')),
                ('educationLevel', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=225, verbose_name='Submitted'), multiplicity=1, rdf_name='http://purl.org/dc/terms/educationLevel', rdf_namespace='http://purl.org/dc/terms/')),
                ('extent', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=225, verbose_name='Extent'), multiplicity=1, rdf_name='http://purl.org/dc/terms/extent', rdf_namespace='http://purl.org/dc/terms/')),
                ('dformat_term', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=225, verbose_name='Format'), multiplicity=1, rdf_name='<built-in method format of Namespace object at 0x7fc43c4722a0>', rdf_namespace='http://purl.org/dc/terms/')),
                ('hasFormat', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=225), multiplicity=1, rdf_name='http://purl.org/dc/terms/hasFormat', rdf_namespace='http://purl.org/dc/terms/')),
                ('hasPart', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=225), multiplicity=1, rdf_name='http://purl.org/dc/terms/hasPart', rdf_namespace='http://purl.org/dc/terms/')),
                ('hasVersion', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=225), multiplicity=1, rdf_name='http://purl.org/dc/terms/hasVersion', rdf_namespace='http://purl.org/dc/terms/')),
                ('identifier_term', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=225, verbose_name='Identifier'), multiplicity=1, rdf_name='http://purl.org/dc/terms/identifier', rdf_namespace='http://purl.org/dc/terms/')),
                ('instructionalMethod', fedoralink.fields.FedoraField(base_field=models.TextField(default=''), multiplicity=1, rdf_name='http://purl.org/dc/terms/instructionalMethod', rdf_namespace='http://purl.org/dc/terms/')),
                ('isFormatOf', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=225), multiplicity=1, rdf_name='http://purl.org/dc/terms/isFormatOf', rdf_namespace='http://purl.org/dc/terms/')),
                ('isPartOf', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=225), multiplicity=1, rdf_name='http://purl.org/dc/terms/isPartOf', rdf_namespace='http://purl.org/dc/terms/')),
                ('isReferencedBy', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=225), multiplicity=1, rdf_name='http://purl.org/dc/terms/isReferencedBy', rdf_namespace='http://purl.org/dc/terms/')),
                ('isReplacedBy', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=225), multiplicity=1, rdf_name='http://purl.org/dc/terms/isReplacedBy', rdf_namespace='http://purl.org/dc/terms/')),
                ('isRequiredBy', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=225), multiplicity=1, rdf_name='http://purl.org/dc/terms/isRequiredBy', rdf_namespace='http://purl.org/dc/terms/')),
                ('issued', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=128, verbose_name='Issued'), multiplicity=1, rdf_name='http://purl.org/dc/terms/issued', rdf_namespace='http://purl.org/dc/terms/')),
                ('isVersionOf', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=225), multiplicity=1, rdf_name='http://purl.org/dc/terms/isVersionOf', rdf_namespace='http://purl.org/dc/terms/')),
                ('language_term', fedoralink.fields.FedoraField(base_field=models.CharField(max_length=128, verbose_name='Language'), multiplicity=1, rdf_name='http://purl.org/dc/terms/language', rdf_namespace='http://purl.org/dc/terms/')),
                ('license', fedoralink.fields.FedoraField(base_field=models.TextField(default='', verbose_name='License'), multiplicity=1, rdf_name='http://purl.org/dc/terms/license', rdf_namespace='http://purl.org/dc/terms/')),
                ('mediator', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=255, verbose_name='Mediator'), multiplicity=1, rdf_name='http://purl.org/dc/terms/mediator', rdf_namespace='http://purl.org/dc/terms/')),
                ('medium', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=255, verbose_name='Medium'), multiplicity=1, rdf_name='http://purl.org/dc/terms/medium', rdf_namespace='http://purl.org/dc/terms/')),
                ('modified', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=128, verbose_name='Issued'), multiplicity=1, rdf_name='http://purl.org/dc/terms/modified', rdf_namespace='http://purl.org/dc/terms/')),
                ('provenance', fedoralink.fields.FedoraField(base_field=models.TextField(default='', verbose_name='Provenance'), multiplicity=1, rdf_name='http://purl.org/dc/terms/provenance', rdf_namespace='http://purl.org/dc/terms/')),
                ('publisher_term', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=255, verbose_name='Publisher'), multiplicity=1, rdf_name='http://purl.org/dc/terms/publisher', rdf_namespace='http://purl.org/dc/terms/')),
                ('references', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=255, verbose_name='References'), multiplicity=1, rdf_name='http://purl.org/dc/terms/references', rdf_namespace='http://purl.org/dc/terms/')),
                ('relation_term', fedoralink.fields.FedoraField(base_field=models.TextField(default='', verbose_name='Relation'), multiplicity=1, rdf_name='http://purl.org/dc/terms/relation', rdf_namespace='http://purl.org/dc/terms/')),
                ('replaces', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=225), multiplicity=1, rdf_name='http://purl.org/dc/terms/replaces', rdf_namespace='http://purl.org/dc/terms/')),
                ('requires', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=225), multiplicity=1, rdf_name='http://purl.org/dc/terms/requires', rdf_namespace='http://purl.org/dc/terms/')),
                ('rights_term', fedoralink.fields.FedoraField(base_field=models.TextField(default='', verbose_name='Rights'), multiplicity=1, rdf_name='http://purl.org/dc/terms/rights', rdf_namespace='http://purl.org/dc/terms/')),
                ('rightsHolder', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=225), multiplicity=1, rdf_name='http://purl.org/dc/terms/rightsHolder', rdf_namespace='http://purl.org/dc/terms/')),
                ('source_term', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=255, verbose_name='Source'), multiplicity=1, rdf_name='http://purl.org/dc/terms/source', rdf_namespace='http://purl.org/dc/terms/')),
                ('spatial', fedoralink.fields.FedoraField(base_field=models.TextField(default='', verbose_name='Spatial'), multiplicity=1, rdf_name='http://purl.org/dc/terms/spatial', rdf_namespace='http://purl.org/dc/terms/')),
                ('subject_term', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=255, verbose_name='Subject'), multiplicity=1, rdf_name='http://purl.org/dc/terms/subject', rdf_namespace='http://purl.org/dc/terms/')),
                ('tableOfContents', fedoralink.fields.FedoraField(base_field=models.TextField(default='', verbose_name='TableOfContents'), multiplicity=1, rdf_name='http://purl.org/dc/terms/tableOfContents', rdf_namespace='http://purl.org/dc/terms/')),
                ('temporal', fedoralink.fields.FedoraField(base_field=models.TextField(default='', verbose_name='Temporal'), multiplicity=1, rdf_name='http://purl.org/dc/terms/temporal', rdf_namespace='http://purl.org/dc/terms/')),
                ('title_term', fedoralink.fields.FedoraField(base_field=models.TextField(default='', verbose_name='Title'), multiplicity=1, rdf_name='http://purl.org/dc/terms/title', rdf_namespace='http://purl.org/dc/terms/')),
                ('type_term', fedoralink.fields.FedoraField(base_field=models.CharField(max_length=128, verbose_name='Type'), multiplicity=1, rdf_name='http://purl.org/dc/terms/type', rdf_namespace='http://purl.org/dc/terms/')),
                ('valid', fedoralink.fields.FedoraField(base_field=models.CharField(default='', max_length=128, verbose_name='Valid'), multiplicity=1, rdf_name='http://purl.org/dc/terms/valid', rdf_namespace='http://purl.org/dc/terms/')),
                ('fedora_id', fedoralink.models.FedoraResourceUrlField(blank=True, null=True, unique=True, verbose_name='Fedora resource URL')),
            ],
            fedora_options={'default_parent': 'dc_dcobject', 'field_options': None, 'primary_rdf_type': 'http://purl.org/dc/elements/1.1/object', 'rdf_namespace': 'http://purl.org/dc/elements/1.1/', 'rdf_types': ['http://purl.org/dc/elements/1.1/object']},
        ),
    ]
